{% set version = "v0.6.0" %}

package:
  name: ifcopenshell
  version: {{ version }}

source:
  url: https://github.com/IfcOpenShell/IfcOpenShell/archive/{{ version }}.tar.gz
  sha256: d11e1fb4b012f8e8717511c8ac97bf3d6cabf957bfdef50f564d19d9976f8e86

build:
  number: 2
  skip: True  # [py2k]

requirements:
  build:
    - cmake
    - ninja
    - swig 3.*
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - boost-cpp
    - occt
    - libxml2
  run:
    - python
    - boost-cpp
    - occt
    - libxml2

test:
  imports:
    - ifcopenshell

about:
  home: http://ifcopenshell.org
  license: LGPL-3.0-or-later
  license_file: COPYING
  summary: 'IfcOpenShell is a library to support the IFC file format'
  description: |
    IfcOpenShell is an open source (LGPL) software library for 
    working with the Industry Foundation Classes (IFC) file format.
  doc_url: http://ifcopenshell.org/
  dev_url: https://github.com/IfcOpenShell/IfcOpenShell

extra:
  recipe-maintainers:
    - looooo
