{% set version = "v0.6.0" %}

package:
  name: ifcopenshell
  version: {{ version }}

source:
  url: https://github.com/IfcOpenShell/IfcOpenShell/archive/{{ version }}.tar.gz
  sha256: 3f90327f1a02a362ebea2c4ec1a0ac26234c150cab60771df2c75a9920004c00

build:
  number: 1
  skip: True  # [py2k]

requirements:
  build:
    - cmake
    - ninja
    - swig 3.*
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - icu
    - boost-cpp
    - occt
    - libxml2
  run:
    - python
    - icu
    - boost-cpp
    - occt
    - libxml2

test:
  imports:
    - ifcopenshell

about:
  home: http://ifcopenshell.org
  license: LGPL-3.0
  license_file: COPYING
  summary: 'IfcOpenShell is a library to support the IFC file format'
  description: |
    IfcOpenShell is an open source (LGPL) software library for 
    working with the Industry Foundation Classes (IFC) file format.
  doc_url: http://ifcopenshell.org/
  dev_url: https://github.com/IfcOpenShell/IfcOpenShell

extra:
  recipe-maintainers:
    - looooo
