{% set version = "v0.6.0" %}

package:
  name: ifcopenshell
  version: {{ version }}

source:
  url: https://github.com/lawsonAGMT/IfcOpenShell/archive/my-v6.0.0.tar.gz
  sha256: a41e014f8b0fa40ea22f04e84e136effeda9392a0b8e024c2a822a0247ac0031

build:
  number: 0
  skip: True  # [py2k]

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - swig 3.*
    - python
    - icu
    - boost-cpp
    - occt
    - libxml2
  run:
    - python
    - icu
    - boost-cpp
    - occt
    - libxml2

test:
  imports:
    - ifcopenshell

about:
  home: http://ifcopenshell.org
  license: LGPL-3.0
  license_file: COPYING
  summary: 'IfcOpenShell is a library to support the IFC file format'
  description: |
    IfcOpenShell is an open source (LGPL) software library for 
    working with the Industry Foundation Classes (IFC) file format.
  doc_url: http://ifcopenshell.org/
  dev_url: https://github.com/IfcOpenShell/IfcOpenShell

extra:
  recipe-maintainers:
    - looooo
