{% set version = "0.5.0-preview2" %}

package:
  name: ifcopenshell
  version: v{{ version }}

source:
  url: https://github.com/IfcOpenShell/IfcOpenShell/archive/v{{ version }}.tar.gz
  sha256: 01c8395995ec4e2ef2fc1fd49cda2dfb99d2c6e679c2a957795630d7b01866d8

build:
  number: 0
  skip: True  # [py2k]

requirements:
  build:
    - cmake
    - ninja
    - swig 3.*
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - icu
    - boost-cpp
    - occt
    - libxml2
  run:
    - python
    - icu
    - boost-cpp
    - occt
    - libxml2

test:
  imports:
    - ifcopenshell

about:
  home: http://ifcopenshell.org
  license: LGPL-3.0
  license_file: COPYING
  summary: 'IfcOpenShell is a library to support the IFC file format'
  description: |
    IfcOpenShell is an open source (LGPL) software library for 
    working with the Industry Foundation Classes (IFC) file format.
  doc_url: http://ifcopenshell.org/
  dev_url: https://github.com/IfcOpenShell/IfcOpenShell

extra:
  recipe-maintainers:
    - looooo
